import { useEffect, useState } from 'react'
import { ApiError, clearStoredApiKey, getVersion, loadStoredApiKey } from './api'
import { ApiKeyGate } from './components/ApiKeyGate'
import { Library } from './components/Library'
import { RootFolders } from './components/RootFolders'
import { ScanStatus } from './components/ScanStatus'
import { Settings } from './components/Settings'
import { Unmatched } from './components/Unmatched'
import { Wanted } from './components/Wanted'
import './App.css'

type View = 'library' | 'unmatched' | 'wanted' | 'root-folders' | 'settings'

export default function App() {
  const [apiKey, setApiKey] = useState<string | null>(() => {
    const stored = loadStoredApiKey()
    return stored || null
  })
  const [view, setView] = useState<View>('library')
  const [libraryKey, setLibraryKey] = useState(0)
  const [authError, setAuthError] = useState(false)

  function handleUnauthorized() {
    clearStoredApiKey()
    setApiKey(null)
    setAuthError(true)
  }

  if (!apiKey) {
    return (
      <ApiKeyGate
        onVerified={(key) => {
          setAuthError(false)
          setApiKey(key)
        }}
      />
    )
  }

  return (
    <AuthedApp
      apiKey={apiKey}
      authError={authError}
      onUnauthorized={handleUnauthorized}
      view={view}
      setView={setView}
      libraryKey={libraryKey}
      onScanFinished={() => setLibraryKey((k) => k + 1)}
    />
  )
}

function AuthedApp({
  apiKey,
  authError,
  onUnauthorized,
  view,
  setView,
  libraryKey,
  onScanFinished,
}: {
  apiKey: string
  authError: boolean
  onUnauthorized: () => void
  view: View
  setView: (v: View) => void
  libraryKey: number
  onScanFinished: () => void
}) {
  // A quick, one-time check that the stored key still works — a key
  // regenerated by hand-editing config.yaml since this browser last
  // opened would otherwise only surface as a confusing 401 on whichever
  // request happens to run first.
  useEffect(() => {
    getVersion(apiKey).catch((err) => {
      if (err instanceof ApiError && err.status === 401) onUnauthorized()
    })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [apiKey])

  return (
    <div className="app">
      {authError && <p className="load-error">Your API key was rejected — enter it again.</p>}
      <header className="app-header">
        <h1>🎵 CantiNode</h1>
        <ScanStatus apiKey={apiKey} onScanFinished={onScanFinished} />
      </header>

      <nav className="tabs">
        <button className={view === 'library' ? 'tab tab-active' : 'tab'} onClick={() => setView('library')}>
          Library
        </button>
        <button className={view === 'unmatched' ? 'tab tab-active' : 'tab'} onClick={() => setView('unmatched')}>
          Unmatched
        </button>
        <button className={view === 'wanted' ? 'tab tab-active' : 'tab'} onClick={() => setView('wanted')}>
          Wanted
        </button>
        <button className={view === 'root-folders' ? 'tab tab-active' : 'tab'} onClick={() => setView('root-folders')}>
          Root Folders
        </button>
        <button className={view === 'settings' ? 'tab tab-active' : 'tab'} onClick={() => setView('settings')}>
          Settings
        </button>
      </nav>

      <main>
        {view === 'library' && <Library key={libraryKey} apiKey={apiKey} />}
        {view === 'unmatched' && <Unmatched apiKey={apiKey} />}
        {view === 'wanted' && <Wanted apiKey={apiKey} />}
        {view === 'root-folders' && <RootFolders apiKey={apiKey} />}
        {view === 'settings' && <Settings apiKey={apiKey} />}
      </main>
    </div>
  )
}
